import { Student, Invoice, Attendance, SubsidyRule, FeeCategory, ApprovalRequest, AuditLog, IntegrationLog, DashboardStats } from '../types';

export const mockStudents: Student[] = [
  {
    id: '1',
    studentCode: 'EDU-2024-001',
    name: 'Ahmad Bin Abdullah',
    ic: '120102-10-1234',
    dateOfBirth: new Date('2012-01-02'),
    guardianId: 'g1',
    guardian: {
      id: 'g1',
      name: 'Abdullah Bin Hassan',
      email: 'abdullah@email.com',
      ic: '800505-10-5678',
      role: 'parent',
      phoneNumber: '+60123456789',
      createdAt: new Date('2024-01-15'),
    },
    centreId: 'c1',
    centre: {
      id: 'c1',
      name: 'Pusat Jagaan Wangsa Maju',
      code: 'WM001',
      address: 'Jalan Wangsa Maju 10, 53300 Kuala Lumpur',
      capacity: 100,
      headId: 'h1',
      head: {
        id: 'h1',
        name: 'Siti Nurhaliza',
        email: 'siti@educentre.my',
        ic: '750101-10-1111',
        role: 'centre_head',
        createdAt: new Date('2023-01-01'),
      },
    },
    status: 'active',
    subsidyCategory: 'B40',
    registrationDate: new Date('2024-01-15'),
    monthlyFee: 800,
    depositAmount: 500,
  },
  {
    id: '2',
    studentCode: 'EDU-2024-002',
    name: 'Fatimah Binti Ismail',
    ic: '130305-14-5678',
    dateOfBirth: new Date('2013-03-05'),
    guardianId: 'g2',
    guardian: {
      id: 'g2',
      name: 'Ismail Bin Ahmad',
      email: 'ismail@email.com',
      ic: '820707-10-9012',
      role: 'parent',
      phoneNumber: '+60198765432',
      createdAt: new Date('2024-02-01'),
    },
    centreId: 'c1',
    centre: {
      id: 'c1',
      name: 'Pusat Jagaan Wangsa Maju',
      code: 'WM001',
      address: 'Jalan Wangsa Maju 10, 53300 Kuala Lumpur',
      capacity: 100,
      headId: 'h1',
      head: {
        id: 'h1',
        name: 'Siti Nurhaliza',
        email: 'siti@educentre.my',
        ic: '750101-10-1111',
        role: 'centre_head',
        createdAt: new Date('2023-01-01'),
      },
    },
    status: 'active',
    subsidyCategory: 'M40',
    registrationDate: new Date('2024-02-01'),
    monthlyFee: 800,
    depositAmount: 500,
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'INV-2023-012',
    studentId: '1',
    student: mockStudents[0],
    amount: 800,
    subsidyAmount: 400,
    netAmount: 400,
    penaltyAmount: 0,
    dueDate: new Date('2023-12-31'),
    status: 'paid',
    issueDate: new Date('2023-12-01'),
    paidAmount: 400,
    description: 'Monthly Fee - December 2023',
  },
  {
    id: 'inv-2',
    invoiceNumber: 'INV-2024-001',
    studentId: '1',
    student: mockStudents[0],
    amount: 800,
    subsidyAmount: 400,
    netAmount: 400,
    penaltyAmount: 0,
    dueDate: new Date('2024-01-31'),
    status: 'paid',
    issueDate: new Date('2024-01-01'),
    paidAmount: 400,
    description: 'Monthly Fee - January 2024',
  },
  {
    id: 'inv-3',
    invoiceNumber: 'INV-2024-002',
    studentId: '1',
    student: mockStudents[0],
    amount: 800,
    subsidyAmount: 400,
    netAmount: 400,
    penaltyAmount: 0,
    dueDate: new Date('2024-02-29'),
    status: 'paid',
    issueDate: new Date('2024-02-01'),
    paidAmount: 400,
    description: 'Monthly Fee - February 2024',
  },
  {
    id: 'inv-4',
    invoiceNumber: 'INV-2024-003',
    studentId: '1',
    student: mockStudents[0],
    amount: 800,
    subsidyAmount: 400,
    netAmount: 400,
    penaltyAmount: 0,
    dueDate: new Date('2024-03-31'),
    status: 'partially_paid',
    issueDate: new Date('2024-03-01'),
    paidAmount: 200,
    description: 'Monthly Fee - March 2024',
  },
  {
    id: 'inv-5',
    invoiceNumber: 'INV-2024-004',
    studentId: '1',
    student: mockStudents[0],
    amount: 800,
    subsidyAmount: 400,
    netAmount: 400,
    penaltyAmount: 0,
    dueDate: new Date('2024-04-30'),
    status: 'pending',
    issueDate: new Date('2024-04-01'),
    paidAmount: 0,
    description: 'Monthly Fee - April 2024',
  },
  {
    id: 'inv-6',
    invoiceNumber: 'INV-2024-005',
    studentId: '1',
    student: mockStudents[0],
    amount: 800,
    subsidyAmount: 400,
    netAmount: 400,
    penaltyAmount: 0,
    dueDate: new Date('2024-05-31'),
    status: 'pending',
    issueDate: new Date('2024-05-01'),
    paidAmount: 0,
    description: 'Monthly Fee - May 2024',
  },
  {
    id: 'inv-7',
    invoiceNumber: 'INV-2024-006',
    studentId: '2',
    student: mockStudents[1],
    amount: 800,
    subsidyAmount: 240,
    netAmount: 560,
    penaltyAmount: 50,
    dueDate: new Date('2024-01-31'),
    status: 'overdue',
    issueDate: new Date('2024-01-01'),
    paidAmount: 0,
    description: 'Monthly Fee - January 2024 + Late Payment Penalty',
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: 'att-1',
    studentId: '1',
    student: mockStudents[0],
    date: new Date('2024-01-15'),
    status: 'present',
    checkInTime: new Date('2024-01-15T08:00:00'),
    checkOutTime: new Date('2024-01-15T17:00:00'),
    method: 'Face ID',
    recordedBy: 'system',
  },
  {
    id: 'att-2',
    studentId: '1',
    student: mockStudents[0],
    date: new Date('2024-01-16'),
    status: 'present',
    checkInTime: new Date('2024-01-16T08:15:00'),
    checkOutTime: new Date('2024-01-16T17:10:00'),
    method: 'QR Code',
    recordedBy: 'system',
  },
  {
    id: 'att-3',
    studentId: '2',
    student: mockStudents[1],
    date: new Date('2024-01-15'),
    status: 'absent',
    method: 'Manual',
    recordedBy: 'admin',
  },
];

export const mockSubsidyRules: SubsidyRule[] = [
  {
    id: 'sub-1',
    category: 'B40',
    percentage: 50,
    maxAmount: 500,
    minIncome: 0,
    maxIncome: 4850,
    isActive: true,
  },
  {
    id: 'sub-2',
    category: 'M40',
    percentage: 30,
    maxAmount: 300,
    minIncome: 4851,
    maxIncome: 10970,
    isActive: true,
  },
  {
    id: 'sub-3',
    category: 'Asnaf',
    percentage: 70,
    maxAmount: 700,
    minIncome: 0,
    maxIncome: 100000,
    isActive: true,
  },
];

export const mockFeeCategories: FeeCategory[] = [
  {
    id: 'fee-1',
    name: 'Infants (0-2 years)',
    centreId: 'c1',
    monthlyFee: 900,
    depositAmount: 500,
    ageGroupMin: 0,
    ageGroupMax: 2,
    isActive: true,
  },
  {
    id: 'fee-2',
    name: 'Toddlers (3-5 years)',
    centreId: 'c1',
    monthlyFee: 800,
    depositAmount: 500,
    ageGroupMin: 3,
    ageGroupMax: 5,
    isActive: true,
  },
  {
    id: 'fee-3',
    name: 'Children (6-12 years)',
    centreId: 'c1',
    monthlyFee: 700,
    depositAmount: 400,
    ageGroupMin: 6,
    ageGroupMax: 12,
    isActive: true,
  },
];

export const mockApprovalRequests: ApprovalRequest[] = [
  {
    id: 'apr-1',
    type: 'fee_adjustment',
    requesterId: 'admin-1',
    requester: {
      id: 'admin-1',
      name: 'Ali Bin Abu',
      email: 'ali@educentre.my',
      ic: '880808-10-8888',
      role: 'centre_admin',
      createdAt: new Date('2023-06-01'),
    },
    status: 'pending',
    amount: 200,
    description: 'Fee adjustment for financial hardship - Student EDU-2024-001',
    requestDate: new Date('2024-01-20'),
    studentId: '1',
    invoiceId: 'inv-2',
  },
  {
    id: 'apr-2',
    type: 'subsidy_override',
    requesterId: 'admin-1',
    requester: {
      id: 'admin-1',
      name: 'Ali Bin Abu',
      email: 'ali@educentre.my',
      ic: '880808-10-8888',
      role: 'centre_admin',
      createdAt: new Date('2023-06-01'),
    },
    approverId: 'h1',
    approver: {
      id: 'h1',
      name: 'Siti Nurhaliza',
      email: 'siti@educentre.my',
      ic: '750101-10-1111',
      role: 'centre_head',
      createdAt: new Date('2023-01-01'),
    },
    status: 'approved',
    amount: 150,
    description: 'Additional subsidy for special needs student',
    requestDate: new Date('2024-01-10'),
    approvalDate: new Date('2024-01-12'),
    comments: 'Approved due to documented special circumstances',
    studentId: '2',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    userId: 'admin-1',
    user: {
      id: 'admin-1',
      name: 'Ali Bin Abu',
      email: 'ali@educentre.my',
      ic: '880808-10-8888',
      role: 'centre_admin',
      createdAt: new Date('2023-06-01'),
    },
    action: 'UPDATE',
    entity: 'Student',
    entityId: '1',
    beforeData: { status: 'pending' },
    afterData: { status: 'active' },
    timestamp: new Date('2024-01-15T10:30:00'),
    ipAddress: '192.168.1.100',
  },
  {
    id: 'log-2',
    userId: 'h1',
    user: {
      id: 'h1',
      name: 'Siti Nurhaliza',
      email: 'siti@educentre.my',
      ic: '750101-10-1111',
      role: 'centre_head',
      createdAt: new Date('2023-01-01'),
    },
    action: 'APPROVE',
    entity: 'ApprovalRequest',
    entityId: 'apr-2',
    beforeData: { status: 'pending' },
    afterData: { status: 'approved', comments: 'Approved due to documented special circumstances' },
    timestamp: new Date('2024-01-12T14:20:00'),
    ipAddress: '192.168.1.50',
  },
];

export const mockIntegrationLogs: IntegrationLog[] = [
  {
    id: 'int-1',
    type: 'IAS_SYNC',
    status: 'success',
    request: { invoiceId: 'inv-1', action: 'create_ar' },
    response: { status: 'posted', arNumber: 'AR-2024-001' },
    retryCount: 0,
    timestamp: new Date('2024-01-01T09:00:00'),
  },
  {
    id: 'int-2',
    type: 'PAYMENT_GATEWAY',
    status: 'failed',
    request: { invoiceId: 'inv-2', amount: 400, method: 'FPX' },
    errorMessage: 'Gateway timeout - retrying',
    retryCount: 2,
    timestamp: new Date('2024-01-15T11:30:00'),
  },
  {
    id: 'int-3',
    type: 'WHATSAPP',
    status: 'success',
    request: { guardianId: 'g1', messageType: 'invoice_reminder' },
    response: { messageId: 'wa-msg-12345', status: 'delivered' },
    retryCount: 0,
    timestamp: new Date('2024-01-20T08:00:00'),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalStudents: 85,
  activeStudents: 82,
  totalRevenue: 68000,
  outstandingAmount: 15600,
  collectionRate: 77.1,
  subsidyUtilization: 34200,
  attendanceRate: 94.5,
  pendingApprovals: 3,
};
