export interface Institute {
  id: string;
  name: string;
  code: string;
  address: string;
  city: string;
  state: string;
  capacity: number;
  students: number;
  status: 'active' | 'inactive';
}

export const malaysianInstitutes: Institute[] = [
  {
    id: '1',
    name: 'Sekolah Agama Bantuan Kerajaan Darul Ulum',
    code: 'SABK-WP-001',
    address: 'Jalan Raja Laut',
    city: 'Kuala Lumpur',
    state: 'Wilayah Persekutuan',
    capacity: 50,
    students: 45,
    status: 'active',
  },
  {
    id: '2',
    name: 'Sekolah Agama Bantuan Kerajaan Al-Amin',
    code: 'SABK-WP-002',
    address: 'Jalan Masjid India',
    city: 'Kuala Lumpur',
    state: 'Wilayah Persekutuan',
    capacity: 60,
    students: 52,
    status: 'active',
  },
  {
    id: '3',
    name: 'Sekolah Agama Bantuan Kerajaan Nurul Hidayah',
    code: 'SABK-WP-003',
    address: 'Jalan Cheras',
    city: 'Cheras',
    state: 'Wilayah Persekutuan',
    capacity: 55,
    students: 48,
    status: 'active',
  },
  {
    id: '4',
    name: 'Sekolah Rendah Agama Integrasi Al-Falah',
    code: 'SRAI-WP-001',
    address: 'Jalan Sentul',
    city: 'Sentul',
    state: 'Wilayah Persekutuan',
    capacity: 45,
    students: 38,
    status: 'active',
  },
  {
    id: '5',
    name: 'Sekolah Rendah Agama Integrasi Darul Ihsan',
    code: 'SRAI-PJ-001',
    address: 'Presint 5',
    city: 'Putrajaya',
    state: 'Wilayah Persekutuan',
    capacity: 40,
    students: 32,
    status: 'active',
  },
  {
    id: '6',
    name: 'Sekolah Agama Bantuan Kerajaan Ar-Raudhah',
    code: 'SABK-SEL-001',
    address: 'Seksyen 7',
    city: 'Shah Alam',
    state: 'Selangor',
    capacity: 65,
    students: 58,
    status: 'active',
  },
  {
    id: '7',
    name: 'Sekolah Agama Bantuan Kerajaan Al-Khairiah',
    code: 'SABK-SEL-002',
    address: 'Seksyen 52',
    city: 'Petaling Jaya',
    state: 'Selangor',
    capacity: 55,
    students: 49,
    status: 'active',
  },
  {
    id: '8',
    name: 'Sekolah Rendah Agama Integrasi Nurul Iman',
    code: 'SRAI-SEL-001',
    address: 'SS15',
    city: 'Subang Jaya',
    state: 'Selangor',
    capacity: 50,
    students: 44,
    status: 'active',
  },
  {
    id: '9',
    name: 'Sekolah Agama Bantuan Kerajaan As-Salam',
    code: 'SABK-SEL-003',
    address: 'Jalan Meru',
    city: 'Klang',
    state: 'Selangor',
    capacity: 48,
    students: 42,
    status: 'active',
  },
  {
    id: '10',
    name: 'Sekolah Agama Bantuan Kerajaan Tahfiz Al-Quran',
    code: 'SABK-SEL-004',
    address: 'Bandar Seri Putra',
    city: 'Kajang',
    state: 'Selangor',
    capacity: 40,
    students: 35,
    status: 'active',
  },
  {
    id: '11',
    name: 'Sekolah Agama Bantuan Kerajaan Darul Falah',
    code: 'SABK-JHR-001',
    address: 'Jalan Skudai',
    city: 'Johor Bahru',
    state: 'Johor',
    capacity: 58,
    students: 51,
    status: 'active',
  },
  {
    id: '12',
    name: 'Sekolah Rendah Agama Integrasi Al-Hidayah',
    code: 'SRAI-JHR-001',
    address: 'Taman Pasir Putih',
    city: 'Pasir Gudang',
    state: 'Johor',
    capacity: 42,
    students: 36,
    status: 'active',
  },
  {
    id: '13',
    name: 'Sekolah Agama Bantuan Kerajaan Nurul Huda',
    code: 'SABK-JHR-002',
    address: 'Jalan Salleh',
    city: 'Muar',
    state: 'Johor',
    capacity: 35,
    students: 28,
    status: 'active',
  },
  {
    id: '14',
    name: 'Sekolah Agama Bantuan Kerajaan Al-Mashoor',
    code: 'SABK-PNG-001',
    address: 'Jalan Macalister',
    city: 'George Town',
    state: 'Pulau Pinang',
    capacity: 52,
    students: 47,
    status: 'active',
  },
  {
    id: '15',
    name: 'Sekolah Rendah Agama Integrasi Darul Naim',
    code: 'SRAI-PNG-001',
    address: 'Jalan Chain Ferry',
    city: 'Butterworth',
    state: 'Pulau Pinang',
    capacity: 45,
    students: 39,
    status: 'active',
  },
  {
    id: '16',
    name: 'Sekolah Agama Bantuan Kerajaan Al-Muttaqin',
    code: 'SABK-PRK-001',
    address: 'Jalan Raja Ekram',
    city: 'Ipoh',
    state: 'Perak',
    capacity: 47,
    students: 41,
    status: 'active',
  },
  {
    id: '17',
    name: 'Sekolah Agama Bantuan Kerajaan Darul Ridzuan',
    code: 'SABK-PRK-002',
    address: 'Jalan Kota',
    city: 'Taiping',
    state: 'Perak',
    capacity: 38,
    students: 31,
    status: 'active',
  },
  {
    id: '18',
    name: 'Sekolah Agama Bantuan Kerajaan Taqwa',
    code: 'SABK-SBH-001',
    address: 'Jalan Tuaran',
    city: 'Kota Kinabalu',
    state: 'Sabah',
    capacity: 50,
    students: 43,
    status: 'active',
  },
  {
    id: '19',
    name: 'Sekolah Rendah Agama Integrasi Darul Aman',
    code: 'SRAI-SBH-001',
    address: 'Jalan Leila',
    city: 'Sandakan',
    state: 'Sabah',
    capacity: 40,
    students: 34,
    status: 'active',
  },
  {
    id: '20',
    name: 'Sekolah Agama Bantuan Kerajaan Al-Ikhlas',
    code: 'SABK-SBH-002',
    address: 'Jalan Dunlop',
    city: 'Tawau',
    state: 'Sabah',
    capacity: 38,
    students: 31,
    status: 'active',
  },
  {
    id: '21',
    name: 'Sekolah Agama Bantuan Kerajaan Darul Ibadah',
    code: 'SABK-SWK-001',
    address: 'Jalan Tun Ahmad Zaidi',
    city: 'Kuching',
    state: 'Sarawak',
    capacity: 48,
    students: 42,
    status: 'active',
  },
  {
    id: '22',
    name: 'Sekolah Rendah Agama Integrasi Al-Furqan',
    code: 'SRAI-SWK-001',
    address: 'Jalan Pujut',
    city: 'Miri',
    state: 'Sarawak',
    capacity: 42,
    students: 36,
    status: 'active',
  },
  {
    id: '23',
    name: 'Sekolah Agama Bantuan Kerajaan Nurul Islam',
    code: 'SABK-SWK-002',
    address: 'Jalan Tun Abang Haji Openg',
    city: 'Sibu',
    state: 'Sarawak',
    capacity: 38,
    students: 32,
    status: 'active',
  },
  {
    id: '24',
    name: 'Sekolah Agama Bantuan Kerajaan Al-Islah',
    code: 'SABK-MLK-001',
    address: 'Jalan Hang Tuah',
    city: 'Melaka',
    state: 'Melaka',
    capacity: 45,
    students: 38,
    status: 'active',
  },
  {
    id: '25',
    name: 'Sekolah Agama Bantuan Kerajaan Darul Ulum',
    code: 'SABK-KDH-001',
    address: 'Jalan Putra',
    city: 'Alor Setar',
    state: 'Kedah',
    capacity: 43,
    students: 37,
    status: 'active',
  },
];
